name: universal_serial
description: "A unified, cross-platform API for USB/UART serial communication across Web, Android, Windows, macOS, and Linux."
version: 0.0.2
homepage: https://github.com/seetherisingazeez/universal_serial
repository: https://github.com/seetherisingazeez/universal_serial
issue_tracker: https://github.com/seetherisingazeez/universal_serial/issues

topics:
  - serial
  - usb
  - hardware
  - cross-platform
  - uart

platforms:
  android:
  ios:
  windows:
  macos:
  linux:
  web:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0
  usb_serial: ^0.5.2
  webserial: ^1.2.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
